# Generated by Django 3.2.6 on 2021-09-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_carts_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
