# Generated by Django 3.2.6 on 2021-09-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_carts_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='products',
            field=models.CharField(max_length=60),
        ),
    ]
