# Generated by Django 3.2.6 on 2021-09-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_carts_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='products',
            field=models.CharField(max_length=50),
        ),
    ]
